#!/bin/bash
echo Read serial port
echo Usage $0 [BaudRate] \(default 4800\)
echo Try 2400, 4800, 9600, 19200, 38400, 57600, 115200, ...
CP=./classes:/home/pi/pi4j/pi4j-distribution/target/distro-contents/lib/pi4j-core.jar
sudo java -cp $CP readserialport.NMEAReader $*

