#!/bin/bash
echo Read serial port
echo Usage $0 [BaudRate] \(default 4800\)
echo Try 2400, 4800, 9600, 19200, 38400, 57600, 115200, ...
CP=./classes
CP=$CP:../AdafruitI2C/classes
CP=$CP:../GPSandSun/classes
CP=$CP:/home/pi/pi4j/pi4j-distribution/target/distro-contents/lib/pi4j-core.jar
CP=$CP:./lib/almanactools.jar
CP=$CP:./lib/geomutil.jar
CP=$CP:./lib/nauticalalmanac.jar
CP=$CP:./lib/nmeaparser.jar
CP=$CP:./lib/coreutilities.jar
sudo java -cp $CP sunservo.SunServoNMEAReader $*
